# Generated by Django 5.0.13 on 2025-03-12 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('measure_of_success', models.TextField()),
                ('kpi_metrics', models.TextField()),
                ('outcome_defined', models.CharField(max_length=10)),
                ('quantifiable_objective', models.FloatField()),
                ('skills_available', models.CharField(max_length=10)),
                ('obstacles_considered', models.CharField(max_length=10)),
                ('thrust_area', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('response', models.TextField()),
                ('final_goal', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
