# Generated by Django 5.2.12 on 2026-04-22 04:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BUObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('goal_text', models.TextField()),
                ('measure_of_success', models.TextField(blank=True, null=True)),
                ('linkage_ta_raw', models.TextField(blank=True, null=True)),
                ('linkage_go_raw', models.TextField(blank=True, null=True)),
                ('source_sheet', models.CharField(max_length=200)),
                ('source_row_no', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['org_unit__name', 'source_row_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='GroupObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('parameter', models.CharField(blank=True, max_length=255, null=True)),
                ('is_sub_heading', models.BooleanField(default=False)),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OrgUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ThrustArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('is_sub_heading', models.BooleanField(default=False)),
                ('parent_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BUObjectiveGOLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('go_code_raw', models.CharField(max_length=100)),
                ('go_code_normalized', models.CharField(db_index=True, max_length=50)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='go_links', to='smart_hr_backend.buobjective')),
            ],
            options={
                'ordering': ['go_code_normalized'],
            },
        ),
        migrations.CreateModel(
            name='BUObjectiveTALink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ta_code_raw', models.CharField(max_length=100)),
                ('ta_code_normalized', models.CharField(db_index=True, max_length=50)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ta_links', to='smart_hr_backend.buobjective')),
            ],
            options={
                'ordering': ['ta_code_normalized'],
            },
        ),
        migrations.AddField(
            model_name='buobjective',
            name='org_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='smart_hr_backend.orgunit'),
        ),
        migrations.CreateModel(
            name='SmartGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.TextField()),
                ('measure_of_success', models.TextField()),
                ('kpi_metrics', models.TextField()),
                ('outcome_defined', models.CharField(max_length=10)),
                ('quantifiable_objective', models.FloatField()),
                ('skills_available', models.CharField(max_length=10)),
                ('obstacles_considered', models.CharField(max_length=10)),
                ('thrust_area', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=255)),
                ('group_objectives', models.TextField(blank=True, null=True)),
                ('additional_sub_category', models.CharField(blank=True, max_length=255, null=True)),
                ('user_bu', models.CharField(blank=True, max_length=100, null=True)),
                ('crosslinked_bus', models.JSONField(blank=True, default=list, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('response', models.TextField()),
                ('final_goal', models.TextField(blank=True, null=True)),
                ('thrust_area_code', models.CharField(blank=True, max_length=50, null=True)),
                ('group_objective_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
