# Generated by Django 5.0.13 on 2025-03-21 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hr_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartgoal',
            name='additional_sub_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='smartgoal',
            name='group_objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
