# Generated by Django 5.2.12 on 2026-03-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hr_backend', '0002_smartgoal_additional_sub_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartgoal',
            name='crosslinked_bus',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='smartgoal',
            name='user_bu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='BUObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bu_name', models.CharField(max_length=100)),
                ('thrust_area', models.CharField(max_length=100)),
                ('group_objective', models.TextField()),
                ('objective_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('bu_name', 'thrust_area', 'group_objective')},
            },
        ),
    ]
