# Generated by Django 5.2.12 on 2026-03-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hr_backend', '0003_add_bu_fields'),
        ('smart_hr_backend', '0003_smartgoal_crosslinked_bus_smartgoal_user_bu_and_more'),
    ]

    operations = [
    ]
