# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hr_backend', '0004_merge_20260310_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartgoal',
            name='user_bu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartgoal',
            name='crosslinked_bus',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
