# Generated by Django 5.2.12 on 2026-03-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hr_backend', '0005_add_bu_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buobjective',
            unique_together=set(),
        ),
    ]
