# Generated by Django 5.2.12 on 2026-03-12 06:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_hr_backend', '0007_create_bu_objectives'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartgoal',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='smartgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartgoal',
            name='group_objective_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartgoal',
            name='thrust_area_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='smartgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
